### ISSUE TITLE
ComputeAndReportContrastsFromSpds broken

### ISSUE THREAD

**Issue by spitschan** [spitschan/SilentSubstitutionToolbox#34]
As of 1192cb7108068f7caac9a233694e0a70cd81e75e, some of my code using ComputeAndReportContrastsFromSpds is broken. @JorisVincent can you look into this?

**Comment by spitschan** [comment]
... and potentially offer some demo code for the new functionality.

**Comment by JorisVincent** [comment]
Bug fixed by https://github.com/spitschan/SilentSubstitutionToolbox/commit/63d5ce1002bc974abf306e5ffd2e39e3f3b49bc2

**Comment by JorisVincent** [comment]
And examples added by https://github.com/spitschan/SilentSubstitutionToolbox/commit/6b7b9825062f4b77b0a8b9c8914a7a71edd7b7d1.

**Comment by spitschan** [comment]
I think the routine is still broken. onsider the following:

```
backgroundSpd = 0.5*ones(401, 1);
modulationSpd = ones(401, 1);
T_receptors = ones(1, 401);

 ComputeAndReportContrastsFromSpds('','',T_receptors,backgroundSpd,modulationSpd,'doPostreceptoral', false)
```

An error is thrown:

```

Cell contents reference from a
non-cell array object.

Error in
ComputeAndReportContrastsFromSpds
(line 63)
        fprintf('  * %s: contrast =
        %0.1f%%\n',receptorStrings{j},100*receptorContrasts(j)); 
```

and 

```

receptorContrasts =

     1
    -1
```

Where it clearly should just be 1x1.

I'm reverting to the old way of calculating it in HEAD for now, but happy to use the `SPDToReceptorContrast` machinery.

**Comment by JorisVincent** [comment]
That error has to do with the `receptorStings`: 

```
% Input:
%    photoreceptorClasses - Names of the photoreceptor classes in a **cell array**.
```

Running the following (with photoreceptorClasses as cell-array) does not throw the error:
```
backgroundSpd = 0.5*ones(401, 1);
modulationSpd = ones(401, 1);
T_receptors = ones(1, 401);

 ComputeAndReportContrastsFromSpds('',{''},T_receptors,backgroundSpd,modulationSpd,'doPostreceptoral', false)
```

**Comment by JorisVincent** [comment]
I'm looking into the other issue now.

**Comment by JorisVincent** [comment]
Other issue was unique to the situation of a single receptor. Fixed now.

**Comment by spitschan** [comment]
Thank you.

On 30 March 2018 17:06:23 Joris Vincent <notifications@github.com> wrote:
Other issue was unique to the situation of a single receptor. Fixed now.
